### ISSUE TITLE
Panning breaks on Chrome 96

### ISSUE THREAD

**Issue by JeffOlivr** [timmywil/panzoom#600] opened 2021-12-21 16:48 UTC
### Describe the bug

Panning started to break on recent versions of Google Chrome/mium.
After moving and clicking the element controlled by Panzoom for a while, it stop panning and instead it will start to zoom in and out.

It was working perfectly in older versions of Chrome, but I didn't realize in which version it stopped working.
Currently, it works fine on Firefox.

### Your environment

- Version of panzoom: 4.4.3 (also tested on 4.4.4)
- Chromium 96.0.4664.110

### Expected behavior

It should keep panning instead of zooming when using the mouse left-button to move around the element/page.

### Actual behavior

It stops panning and it starts to zoom in and out after moving around for a while.

If you have `disableZoom: true`, nothing will happen, the element will simply stop moving or zooming.

### Steps to reproduce

[JSFiddle Demo](https://jsfiddle.net/3wgtqsro/9/)

It happens kinda randomly. Move the element around, zoom with the mouse wheel, move the element again and, eventually, panning will stop working.

Also, `zoomWithWheel` it's not the problem. Even if you don't bind the event, the bug still occurs.

**Comment by timmywil** [comment] 2021-12-21 19:23
Thanks for opening an issue. I'm not able to reproduce this, but is it possible you're using a trackpad and maybe a second touch is getting in there? That *could* switch it to pinch zooming rather than panning (zoomWithWheel would not need to be bound). Anyway, will close this as works for me unless I can also reproduce it at some point. Sorry I can't be more help.

**Closed by timmywil** 2021-12-21 19:23 UTC

**Comment by JeffOlivr** [comment] 2021-12-21 20:40
Hey Timmy, thank you for the quick response.

I just tested on Windows and on a Linux DE using X11. It's working fine there, I guess it's some weird Wayland shenanigans.

Thank you again!
